[package]
authors = [ "The syscall.rs Project Developers" ]
description = "Raw system calls"
documentation = "https://docs.rs/sc"
keywords = ["syscall", "system", "call"]
license = "MIT OR Apache-2.0"
name = "sc"
readme = "README.md"
repository = "https://github.com/japaric/syscall.rs"
version = "0.2.6"
